export const typstLayout = {
  pageMargin: '15mm',
  zeroSpacing: '0mm',
  annual: {
    cardHeight: '160mm',
    cardWidth: '135mm',
    cardStackTopGap: '20mm',
    titleFontSize: '10mm',
    titleOffsetY: '0mm',
    titleBottomGap: '1mm',
    monthGap: '5mm',
    monthHeight: '35mm',
    monthLabelFontSize: '7mm',
    monthLabelHeight: '10mm',
    monthLabelOffsetY: '-1mm',
    monthLabelPaddingLeft: '0.5mm',
    weekdayFontSize: '3mm',
    weekdayHeight: '4mm',
    weekdayStrokeWidth: '0.5mm',
    dateFontSize: '3.5mm',
    dateRowHeight: '3.5mm',
    dateRows: 6,
    dateTopPadding: '1mm',
    gridGutter: '0mm',
    cellInset: '0mm',
  },
  monthly: {
    cardHeight: '80mm',
    cardWidth: '135mm',
    cardStackGap: '0mm',
    cardStackTopGap: '10mm',
    titleFontSize: '8mm',
    titleOffsetY: '0mm',
    titlePaddingBottom: '2.5mm',
    weekdayFontSize: '3.5mm',
    weekdayInsetY: '1.5mm',
    dateFontSize: '5.5mm',
    dateGridHeight: '60mm',
    datePaddingTop: '1mm',
    datePaddingLeft: '1mm',
    holidayAreaHeight: '4mm',
    holidayFontSize: '2.8mm',
    holidayPaddingBottom: '1mm',
    tableStrokeWidth: '0.5mm',
    tableInset: '0mm',
    gridGutter: '0mm',
  },
} as const;
